major/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movie_review.urls')),
    
]

movie_review/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'movie_review'

urlpatterns = [
    path("", views.index, name='welcome_page'),
    path("instruction/", views.instructions, name='instructions'),
    path("movies/", views.movies_page, name='movies'),
    path("movie_button/", views.movie_play_button, name='movie_button'),
    path("analysis_page/", views.movie_analysis_button, name='movie_analysis_button'),
    path("analysis_page/", views.analysis, name='analysis_page'),


]

movie_review/models.py
from django.db import models

# Create your models here.

movie_review/views.py
from django.shortcuts import render
from subprocess import run, PIPE

import os, sys

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
def index(request):
    return render(request, 'homepage.html')


def instructions(request):
    return render(request, 'instruction.html')

# for the movie_play and working page
def movies_page(request):
    return render(request, 'movie_play.html')

def movie_play_button(request):
    file_path = "mdls/working.py"
    u = os.path.join(BASE_DIR, file_path)
    out = run([sys.executable, u], shell=False, stdout=PIPE)
    return render(request, 'movie_play.html', {'modelfile': out.stdout})

# this button run analysis.py and render analysis page
def movie_analysis_button(request):
    file_path = "mdls/analysis.py"
    u = os.path.join(BASE_DIR, file_path)
    out = run([sys.executable, u], shell=False, stdout=PIPE)
    return render(request, 'analysis_page.html', {'imgfile': out.stdout})

# show the analysis and score page
def analysis(request):
    # analysis page will be defined here
    return render(request, 'analysis_page.html')

movie_review/templates/analysis_page.html
{% extends 'base.html' %}

{% block content %}
    {% load static %}
    <img src="{% static 'images/scatter_plot.png' type='img/png' %}" alt="scatter plot">
    <img src="{% static 'images/box_plot.png' type='img/png' %}" alt="box plot">
    <img src="{% static 'images/violin_plot.png' type='img/png' %}" alt="violin plot">
    <img src="{% static 'images/pie_plot.png' type='img/png' %}" alt="pie plot">
    <form method="POST">
        {% csrf_token %}
        {% if imgfile %}
            <h3>{{ imgfile | safe }}</h3>
        {% endif %}
    </form>
    <a href="/">back_to_home</a>
{% endblock %}

movie_review/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    {% load static %}
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>
  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="#" class="brand-logo">___ MovieReview </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="instruction/">Instruction</a></li>
          <li><a href="homepage.html">Home</a></li>
        </ul>
      </div>
    </nav>
    <div class="container">
    {% block content %}
      replace me
    {% endblock %}
    </div>

  </body>
</html>

movie_review/templates/homepage.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome to Movie Review with Facial Expression</h2>
  <h3> Here we are tring to give review to a movie with your live expressions.
  </h3>
  <br>
  <a href="movies/">start here</a>
  <br>
  <br>
  <br>
{% endblock %}

movie_review/templates/instruction.html
{% extends 'base.html' %}

{% block content %}
    <h2>Instructions:</h2>
    <h3>
        from home page click on start here this will take you to movie page.
        on movie page click start system button and when your webcam is onn start the video
        enjoy the video
        when it is completed press 'q'
        the click analysis and it will show you the analysis page
        click on 'back to home' for going back to the home.
        thankyou.
    </h3>
    <br>
    <br>
    <h3>Nothing except the expressions are saved on server. We do not save images or videos.
    </h3>

{% endblock %}

movie_review/templates/movie_play.html
{% extends 'base.html' %}
<!-- https://drive.google.com/open?id=1Yg9chvTklqmKUgcBS6J47K_mle2eY8EI -->
{% block content %}
  {% load static %}
  <br>
  <br>
  <!-- this is to play video from with link use /embed/ in youtube link -->
  <iframe width="625" height="450" src="https://www.youtube.com/embed/AkLnj5pJtDI"
           title="Movie" frameborder="0" allowfullscreen></iframe>
  <!--
  this was to play video from server
  <video width='720' height= '600' controls>
    <source src="{% static 'videos/some.mp4' type='video/mp4' %}">
      Your browser does not support the video tag.
  </video>
  -->

  <br>
  <br>
  <form action="{% url 'movie_review:movie_button' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Start System">
  </form>
  <form action="{% url 'movie_review:movie_analysis_button' %}" method="post">
    {% csrf_token %}
    <input type="submit" value="analysis page">
  </form>
{% endblock %}